ALTER TABLE settings
  ADD COLUMN IF NOT EXISTS tts_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tts_voice   TEXT,
  ADD COLUMN IF NOT EXISTS tts_speed   NUMERIC NOT NULL DEFAULT 1.0;
